//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion.Presentacion.ServicioAutentificador {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAutentificador.Autentificador1")]
    public interface Autentificador1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autentificador1/Autentificar", ReplyAction="http://tempuri.org/Autentificador1/AutentificarResponse")]
        bool Autentificar(string user, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Autentificador1Channel : Aplicacion.Presentacion.ServicioAutentificador.Autentificador1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Autentificador1Client : System.ServiceModel.ClientBase<Aplicacion.Presentacion.ServicioAutentificador.Autentificador1>, Aplicacion.Presentacion.ServicioAutentificador.Autentificador1 {
        
        public Autentificador1Client() {
        }
        
        public Autentificador1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Autentificador1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Autentificador1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Autentificador1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Autentificar(string user, string pass) {
            return base.Channel.Autentificar(user, pass);
        }
    }
}
